import { Mentor } from '@/types';

export const mentors: Mentor[] = [
  {
    id: '1',
    name: 'Coda Jones',
    university: 'University of Michigan',
    position: 'Midfielder',
    year: 'Freshman',
    price: 65,
    rating: 4.9,
    reviewCount: 42,
    location: { city: 'Frisco', state: 'TX' },
    bio: 'Big10 Freshman of the Year with expertise in technical skills and game strategy.',
    achievements: ['Big10 Freshman of the Year', 'Team Captain'],
    avatar: '/avatars/coda.jpg',
    available: true,
    sessionLength: 60,
    conference: 'Big Ten'
  },
  {
    id: '2',
    name: 'Taylor Johnson',
    university: 'UNC Chapel Hill',
    position: 'Midfielder',
    year: 'Junior',
    price: 60,
    rating: 4.8,
    reviewCount: 36,
    location: { city: 'Chapel Hill', state: 'NC' },
    bio: 'ACC All-Academic Team member specializing in leadership and mental preparation.',
    achievements: ['ACC All-Academic Team', 'Conference Finalist'],
    avatar: '/avatars/taylor.jpg',
    available: true,
    sessionLength: 45,
    conference: 'ACC'
  },
  {
    id: '3',
    name: 'Alexis Thompson',
    university: 'UCLA',
    position: 'Defender',
    year: 'Senior',
    price: 70,
    rating: 4.9,
    reviewCount: 51,
    location: { city: 'Los Angeles', state: 'CA' },
    bio: 'Pac-12 Defensive Player of the Year with expertise in defensive positioning and leadership.',
    achievements: ['Pac-12 Defensive Player of the Year', 'All-American'],
    avatar: '/avatars/alexis.jpg',
    available: true,
    sessionLength: 60,
    conference: 'Pac-12'
  },
  {
    id: '4',
    name: 'Zoe Robinson',
    university: 'Florida State',
    position: 'Goalkeeper',
    year: 'Junior',
    price: 65,
    rating: 4.7,
    reviewCount: 29,
    location: { city: 'Tallahassee', state: 'FL' },
    bio: 'ACC All-Tournament Team goalkeeper specializing in shot-stopping and distribution.',
    achievements: ['ACC All-Tournament Team', 'Clean Sheet Record Holder'],
    avatar: '/avatars/zoe.jpg',
    available: true,
    sessionLength: 45,
    conference: 'ACC'
  },
  {
    id: '5',
    name: 'Maya Patel',
    university: 'Stanford',
    position: 'Forward',
    year: 'Sophomore',
    price: 75,
    rating: 4.8,
    reviewCount: 33,
    location: { city: 'Palo Alto', state: 'CA' },
    bio: 'Pac-12 Rising Star with expertise in attacking plays and finishing.',
    achievements: ['Pac-12 Rising Star', 'Leading Goal Scorer'],
    avatar: '/avatars/maya.jpg',
    available: true,
    sessionLength: 60,
    conference: 'Pac-12'
  }
];
